export const toClientResponse = (client: any) => ({
  id: client.id,
  firstName: client.firstName,
  middleName: client.middleName,
  lastName: client.lastName,
  email: client.email,
  phone: client.phone,
  dob: client.dob,
  gender: client.gender,
  maritalStatus: client.maritalStatus,
  pan: client.pan,
  aadhaar: client.aadhaar,
  occupation: client.occupation,
  addressLine1: client.addressLine1,
  addressLine2: client.addressLine2,
  city: client.city,
  state: client.state,
  pincode: client.pincode,
  notes: client.notes,
  isActive: client.isActive,
  createdAt: client.createdAt,
  updatedAt: client.updatedAt,
});
